AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PlantUML Serverless API

Globals:
  Function:
    Runtime: java8
    Timeout: 20
    MemorySize: 512

Resources:
  PngFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.PngHandler::handleRequest
      CodeUri: !Ref paramCodeUri
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /png/{encodedUml}
            Method: get

  ImgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.PngHandler::handleRequest
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /img/{encodedUml}
            Method: get

  SvgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.SvgHandler::handleRequest
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /svg/{encodedUml}
            Method: get

  TxtFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.TxtHandler::handleRequest
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /txt/{encodedUml}
            Method: get

  MapFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.MapHandler::handleRequest
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /map/{encodedUml}
            Method: get

  SyntaxFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nitor.plantuml.lambda.SyntaxHandler::handleRequest
      Timeout: 20
      CodeUri: target/plantuml-serverless-0.0.2.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /check/{encodedUml}
            Method: get