AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PlantUML Serverless – Lambda Function URLs (IAM‑authenticated)
Parameters:
  Env:                   # <─ the parameter you'll pass on deploy
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Default: dev
    Description: Deployment environment tag used in resource names.
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  PlantUmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub plantuml-render-${Env}
      PackageType: Image
      ImageConfig:
        Command: [ "tech.architechsolutions.plantuml.lambda.MainHandler::handleRequest" ]
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: [ "*" ]
          AllowMethods: [ POST ]
          AllowHeaders: [ "Content-Type", "Authorization" ]
      Environment:
        Variables:
          ENV: !Ref Env
    Metadata:
      DockerTag: lambdacontainer-sam
      DockerContext: ./
      Dockerfile: lambdacontainer/Dockerfile
  
Outputs:
  PlantUmlFunctionUrl:
    Description: Lambda Function URL for PlantUML API (IAM protected)
    Value: !GetAtt PlantUmlFunctionUrl.FunctionUrl


